quarkus.http.port=8085
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
transfer-consumer.url=http://localhost:8082

mp.messaging.incoming.transfers-created.connector=smallrye-kafka
mp.messaging.incoming.transfers-created.topic=transfers.created
mp.messaging.incoming.transfers-created.bootstrap.servers=localhost:9092
mp.messaging.incoming.transfers-created.group.id=message-ops-service
mp.messaging.incoming.transfers-created.auto.offset.reset=earliest
mp.messaging.incoming.transfers-created.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

mp.messaging.incoming.transfers-dlt.connector=smallrye-kafka
mp.messaging.incoming.transfers-dlt.topic=transfers.created.DLT
mp.messaging.incoming.transfers-dlt.bootstrap.servers=localhost:9092
mp.messaging.incoming.transfers-dlt.group.id=message-ops-service-dlt
mp.messaging.incoming.transfers-dlt.auto.offset.reset=earliest
mp.messaging.incoming.transfers-dlt.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

mp.messaging.incoming.processed-transfers.connector=smallrye-kafka
mp.messaging.incoming.processed-transfers.topic=consumer.processed-transfers
mp.messaging.incoming.processed-transfers.bootstrap.servers=localhost:9092
mp.messaging.incoming.processed-transfers.group.id=message-ops-service-processed-transfers
mp.messaging.incoming.processed-transfers.auto.offset.reset=earliest
mp.messaging.incoming.processed-transfers.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

mp.messaging.outgoing.transfers-replay.connector=smallrye-kafka
mp.messaging.outgoing.transfers-replay.topic=transfers.created
mp.messaging.outgoing.transfers-replay.bootstrap.servers=localhost:9092
mp.messaging.outgoing.transfers-replay.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.transfers-replay.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
